server:
  servlet:
    context-path: /client
  port: 9095

spring:
  thymeleaf:
    cache: false

logging:
  level:
    root: info
    org:
      springframework:
        web: info
keycloak:
  server:
    url: http://localhost:8080
democlient:
  authorization:
    endpoint: ${keycloak.server.url}/auth/realms/workshop/protocol/openid-connect/auth
    clientid: demo-client
    response-type: code
    redirect-uri: http://localhost:${server.port}/client/callback
    scope: offline_access
  token:
    endpoint: ${keycloak.server.url}/auth/realms/workshop/protocol/openid-connect/token
    clientid: demo-client
    client-secret: a450e87e-0150-4b52-92f5-76993506689f
    redirect-uri: http://localhost:${server.port}/client/callback
  introspection:
    endpoint: ${keycloak.server.url}/auth/realms/workshop/protocol/openid-connect/token/introspect


